import mergeNames from './utils/mergeNames';
import { colors, typography } from './styles';
import processClassName from './processClassName';
import toKebobCase from './toKebobCase';
import tokenGroupTypeToName from './tokenGroupTypeToName';
import tokensetTypeToName from './tokensetTypeToName';
import getIcon, {Icons} from './icons';
import findTokenViaIndex from './utils/findTokenViaIndex';
import cleanName from './utils/cleanName';
import findToken, {findTokenViaStyleId} from './utils/findToken';
import Validator, {
  ValidatorSuccess,
  Validation,
  ValidationLocation,
} from './validator/Validator';
import ValidationWorker from './validator/ValidationWorker';
import {
  dtColorToCss,
  validColor,
  returnValidColor,
  hexToRgb,
  rgbToHex,
  rgbFractionToHex,
  hexAlphaToCss,
} from './utils/colorUtils';
import cleanAndSortTokens from './utils/cleanAndSortTokens';
import colorContrastAda, 
{ 
  AdaColorContrastResult,
} from './utils/adaCompliance';
import isToken from './utils/isToken';
import {
  MessageName,
  DesignTokensResult,
  FileCreateResults,
  MessageRequest,
  MessageRequestStyle,
  State,
  CoreProps,
  GlobalData,
  GitHubSettings,
  TokenGroup,
  TokenGroupLookup,
  TokenGroupCategorizedLookup,
  defaultTokenGroup,
  defaultGlobalData,
  defaultTokenGroupLookup,
  widgetVersion,
  SetterString,
  SetterNumber,
  SetterBoolean,
  SetterStringArray,
  DesignSystemWidget,
  DesignTokensModel,
  TokenSet,
  TokenSetType,
  TokenSetCategory,
  FigmaPaintStyle,
  SelectDropDown,
} from './types/types';
import {
  DTToken,
  DTTokenType,
  DTColor,
  DTColorToken,
  DTCustomToken,
  DTBreakpointToken,
  DTShadowToken,
  DTBorderToken,
  DTStrokeStyleToken,
  DTStrokeStyleTokenValues,
  DTTransitionToken,
  DTGradientToken,
  DTDimensionToken,
  DTTypographyToken,
  DTComponentToken,
  DTSpacingToken,
  DTFontFamilyToken,
  DTFontWeightTokenValues,
  DTFontStyleToken,
  DTCubicBezierToken,
  DTPercentToken,
  DTDurationToken,
  DTFileToken,
} from './types/designTokenTypes';

import {
  DSys,
  DSysLevel,
  DSysSheetGroupNames,
  DSysSheet,
  DSysGroupType,
  DSysColorGroup,
  DSysTypographyGroup,
  DSysEffectGroup,
  DSysIconGroup,
  DSysComponentsGroup,
  DSysSpacingGroup,
  DSysCustomGroup,
  DSysBreakpointGroup,
  DSysUndeterminedGroup,
  DSysGroup,
  DSysTokenset,
  DSysColorTokenset,
  DSysTypographyTokenset,
  DSysEffectTokenset,
  DSysIconTokenset,
  DSysComponentsTokenset,
  DSysSpacingTokenset,
  DSysCustomTokenset,
  DSysCustomToken,
  DSysBreakpointTokenset,
  DSysBreakpointToken,
  DSysUndeterminedTokenset,
  DSysTokensetBase,
  DSysToken,
  DSysColorToken,
  DSysDimensionToken,
  DSysSpacingToken,
  DSysTypographyToken,
  DSysComponentToken,
  DSysSvgToken,
  DSysFontFamilyToken,
  DSysFontWeightToken,
  DSysFontStyleToken,
  DSysStrokeStyleToken,
  DSysBorderToken,
  DSysDurationToken,
  DSysCubicBezierToken,
  DSysShadowToken,
  DSysBlurToken,
  DSysTransitionToken,
  DSysGradientToken,
  DSysPercentToken,
  DSysFileToken,
} from './types/designSystemTypes';


export type {
  ValidatorSuccess, 
  Validation,
  DesignTokensResult,
  FileCreateResults,
  
  AdaColorContrastResult,

  FigmaPaintStyle,
  SelectDropDown,

  State,
  CoreProps,
  GlobalData,
  GitHubSettings,
  TokenGroup,
  TokenGroupLookup,
  TokenGroupCategorizedLookup,
  widgetVersion,
  SetterString,
  SetterNumber,
  SetterBoolean,
  SetterStringArray,
  DesignSystemWidget,
  DesignTokensModel,
  TokenSet,
  TokenSetType,
  TokenSetCategory,

  DTToken,
  DTColor,
  DTColorToken,
  DTCustomToken,
  DTBreakpointToken,
  DTShadowToken,
  DTBorderToken,
  DTStrokeStyleToken,
  DTStrokeStyleTokenValues,
  DTTransitionToken,
  DTGradientToken,
  DTDimensionToken,
  DTTypographyToken,
  DTComponentToken,
  DTSpacingToken,
  DTFontFamilyToken,
  DTFontWeightTokenValues,
  DTFontStyleToken,
  DTCubicBezierToken,
  DTPercentToken,
  DTDurationToken,
  DTFileToken,

  DSys,
  DSysSheet,
  DSysColorGroup,
  DSysTypographyGroup,
  DSysEffectGroup,
  DSysIconGroup,
  DSysComponentsGroup,
  DSysSpacingGroup,
  DSysCustomGroup,
  DSysBreakpointGroup,
  DSysUndeterminedGroup,
  DSysGroup,
  DSysTokenset,
  DSysColorTokenset,
  DSysTypographyTokenset,
  DSysEffectTokenset,
  DSysIconTokenset,
  DSysComponentsTokenset,
  DSysSpacingTokenset,
  DSysCustomTokenset,
  DSysBreakpointTokenset,
  DSysUndeterminedTokenset,
  DSysTokensetBase,
  DSysToken,
  DSysColorToken,
  DSysDimensionToken,
  DSysSpacingToken,
  DSysCustomToken,
  DSysBreakpointToken,
  DSysTypographyToken,
  DSysComponentToken,
  DSysSvgToken,
  DSysFontFamilyToken,
  DSysFontWeightToken,
  DSysFontStyleToken,
  DSysStrokeStyleToken,
  DSysBorderToken,
  DSysDurationToken,
  DSysCubicBezierToken,
  DSysShadowToken,
  DSysBlurToken,
  DSysTransitionToken,
  DSysGradientToken,
  DSysPercentToken,
  DSysFileToken,
}

export {
  Validator,
  ValidationWorker,
  ValidationLocation,
  DSysLevel,
  DSysSheetGroupNames,
  DSysGroupType,
  DTTokenType,
  MessageRequest,
  MessageRequestStyle,
  findTokenViaIndex,
  findToken,
  findTokenViaStyleId,
  MessageName,

  cleanName,

  colors,
  typography,
  mergeNames,
  processClassName,
  toKebobCase,
  tokenGroupTypeToName,
  tokensetTypeToName,
  getIcon, Icons,
  dtColorToCss,
  validColor,
  returnValidColor,
  hexToRgb,
  rgbToHex,
  rgbFractionToHex,
  hexAlphaToCss,

  isToken,
  cleanAndSortTokens,
  colorContrastAda,
  
  defaultTokenGroup,
  defaultGlobalData,
  defaultTokenGroupLookup,
};