import mergeNames from './utils/mergeNames';
import { colors, typography } from './styles';
import processClassName from './processClassName';
import toKebobCase from './toKebobCase';
import tokenGroupTypeToName from './tokenGroupTypeToName';
import tokensetTypeToName from './tokensetTypeToName';
import getIcon, {Icons} from './icons';
import findTokenViaIndex from './utils/findTokenViaIndex';
import findToken from './utils/findToken';
import Validator, {
  ValidatorSuccess,
  Validation,
  ValidationLocations,
  getId,
} from './validator/Validator';
import {
  dtColorToCss,
  validColor,
  returnValidColor,
  hexToRgb,
  rgbToHex,
  rgbFractionToHex,
} from './utils/colorUtils';
import cleanAndSortTokens from './utils/cleanAndSortTokens';
import colorContrastAda, 
{ 
  AdaColorContrastResult,
} from './utils/adaCompliance';
import {
  MessageName,
  MessageRequest,
  MessageRequestStyle,
  State,
  CoreProps,
  GlobalData,
  GitHubSettings,
  TokenGroup,
  TokenGroupLookup,
  defaultTokenGroup,
  defaultGlobalData,
  defaultTokenGroupLookup,
  widgetVersion,
  SetterString,
  SetterNumber,
  SetterBoolean,
  SetterStringArray,
  DesignSystemWidget,
  DesignTokensModel,
  TokenSet,
  TokenSetType,
  TokenSetCategory,
  FigmaPaintStyle,
} from './types/types';
import {
  DTToken,
  DTTokenType,
  DTColor,
  DTColorToken,
  DTShadowToken,
  DTBorderToken,
  DTStrokeStyleToken,
  DTStrokeStyleTokenValues,
  DTTransitionToken,
  DTGradientToken,
  DTDimensionToken,
  DTTypographyToken,
  DTFontFamilyToken,
  DTFontWeightTokenValues,
  DTFontStyleToken,
  DTCubicBezierToken,
  DTPercentToken,
  DTDurationToken,
  DTFileToken,
} from './types/designTokenTypes';

import {
  DSys,
  DSysLevel,
  DSysSheet,
  DSysGroupType,
  DSysColorGroup,
  DSysTypographyGroup,
  DSysEffectGroup,
  DSysIconGroup,
  DSysComponentsGroup,
  DSysSpacingGroup,
  DSysLayoutGroup,
  DSysColumnLayoutGroup,
  DSysUndeterminedGroup,
  DSysGroup,
  DSysTokenset,
  DSysColorTokenset,
  DSysTypographyTokenset,
  DSysEffectTokenset,
  DSysIconTokenset,
  DSysComponentsTokenset,
  DSysSpacingTokenset,
  DSysLayoutTokenset,
  DSysColumnLayoutTokenset,
  DSysUndeterminedTokenset,
  DSysTokensetBase,
  DSysToken,
  DSysColorToken,
  DSysDimensionToken,
  DSysTypographyToken,
  DSysFontFamilyToken,
  DSysFontWeightToken,
  DSysFontStyleToken,
  DSysStrokeStyleToken,
  DSysBorderToken,
  DSysDurationToken,
  DSysCubicBezierToken,
  DSysShadowToken,
  DSysTransitionToken,
  DSysGradientToken,
  DSysPercentToken,
  DSysFileToken,
} from './types/designSystemTypes';


export type {
  ValidatorSuccess, 
  Validation, ValidationLocations,

  AdaColorContrastResult,

  FigmaPaintStyle,

  MessageName,
  State,
  CoreProps,
  GlobalData,
  GitHubSettings,
  TokenGroup,
  TokenGroupLookup,
  widgetVersion,
  SetterString,
  SetterNumber,
  SetterBoolean,
  SetterStringArray,
  DesignSystemWidget,
  DesignTokensModel,
  TokenSet,
  TokenSetType,
  TokenSetCategory,

  DTToken,
  DTColor,
  DTColorToken,
  DTShadowToken,
  DTBorderToken,
  DTStrokeStyleToken,
  DTStrokeStyleTokenValues,
  DTTransitionToken,
  DTGradientToken,
  DTDimensionToken,
  DTTypographyToken,
  DTFontFamilyToken,
  DTFontWeightTokenValues,
  DTFontStyleToken,
  DTCubicBezierToken,
  DTPercentToken,
  DTDurationToken,
  DTFileToken,

  DSys,
  DSysSheet,
  DSysColorGroup,
  DSysTypographyGroup,
  DSysEffectGroup,
  DSysIconGroup,
  DSysComponentsGroup,
  DSysSpacingGroup,
  DSysLayoutGroup,
  DSysColumnLayoutGroup,
  DSysUndeterminedGroup,
  DSysGroup,
  DSysTokenset,
  DSysColorTokenset,
  DSysTypographyTokenset,
  DSysEffectTokenset,
  DSysIconTokenset,
  DSysComponentsTokenset,
  DSysSpacingTokenset,
  DSysLayoutTokenset,
  DSysColumnLayoutTokenset,
  DSysUndeterminedTokenset,
  DSysTokensetBase,
  DSysToken,
  DSysColorToken,
  DSysDimensionToken,
  DSysTypographyToken,
  DSysFontFamilyToken,
  DSysFontWeightToken,
  DSysFontStyleToken,
  DSysStrokeStyleToken,
  DSysBorderToken,
  DSysDurationToken,
  DSysCubicBezierToken,
  DSysShadowToken,
  DSysTransitionToken,
  DSysGradientToken,
  DSysPercentToken,
  DSysFileToken,
}

export {
  Validator,
  DSysLevel,
  DSysGroupType,
  DTTokenType,
  MessageRequest,
  MessageRequestStyle,
  findTokenViaIndex,
  findToken,

  colors,
  typography,
  mergeNames,
  processClassName,
  toKebobCase,
  tokenGroupTypeToName,
  tokensetTypeToName,
  getIcon, Icons,
  getId,
  dtColorToCss,
  validColor,
  returnValidColor,
  hexToRgb,
  rgbToHex,
  rgbFractionToHex,

  cleanAndSortTokens,
  colorContrastAda,
  
  defaultTokenGroup,
  defaultGlobalData,
  defaultTokenGroupLookup,
};